[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install --prefix frontend --include=dev",
  "npm install --prefix backend"
]

[phases.build]
cmds = [
  "npm run build --prefix frontend",
  "node scripts/copy-build.js"
]

[start]
cmd = "cd backend && NODE_ENV=production node server.js"
